apiVersion: v1
kind: ConfigMap
metadata:
  name: donation-service-config
  namespace: solidarytech
  labels:
    app: donation-service
data:
  PORT: "8082"
  AWS_REGION: "us-east-1"
  # Atualize com a URL real da fila SQS provisionada pelo Terraform
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/510818802086/solidary-donations"
