apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
images:
  - name: donation-service-image
    newName: PLACEHOLDER_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/donation-service
    newTag: latest
